### ISSUE TITLE
panic: arithmetic operation overflowed with data > 4GB

### ISSUE THREAD

**Issue by flying-sheep** [alexcrichton/flate2-rs#30]
i get this traceback when unzipping data >4GB

```traceback
thread '<main>' panicked at 'arithmetic operation overflowed', ~/.cargo/registry/src/github.com-0a35038f75765ae4/flate2-0.2.9/src/crc.rs:28
stack backtrace:
   1:     0x7fa79e39b4a9 - sys::backtrace::tracing::imp::write::he18882fa84e6b00ePnt
   2:     0x7fa79e39a688 - panicking::on_panic::h495226a97f084523enx
   3:     0x7fa79e38f69e - sys_common::unwind::begin_unwind_inner::h7a4ee06c0d57e26affs
   4:     0x7fa79e38fb88 - sys_common::unwind::begin_unwind_fmt::hb590a1df1c16a800les
   5:     0x7fa79e399f01 - rust_begin_unwind
   6:     0x7fa79e3ca70f - panicking::panic_fmt::hc3363d565c1048da4HJ
   7:     0x7fa79e3c68f8 - panicking::panic::h14af70be4f3d4feaBGJ
   8:     0x7fa79e308ed5 - crc::Crc::update::h44b516d2a74907c79aa
                        at ~/.cargo/registry/src/github.com-0a35038f75765ae4/flate2-0.2.9/src/crc.rs:28
   9:     0x7fa79e096bfd - crc::CrcReader<R>.Read::read::h13621940182568327352
                        at ~/.cargo/registry/src/github.com-0a35038f75765ae4/flate2-0.2.9/src/crc.rs:47
  10:     0x7fa79e0966df - gz::DecoderReader<R>.Read::read::h5470388900186957621
                        at ~/.cargo/registry/src/github.com-0a35038f75765ae4/flate2-0.2.9/src/gz.rs:446
  11:     0x7fa79e0964c9 - io::buffered::BufReader<R>.BufRead::fill_buf::h13060170593286078394
                        at ../src/libstd/io/buffered.rs:188
  12:     0x7fa79e09606f - io::read_until::h9599120926166658730
                        at ../src/libstd/io/mod.rs:1170
  13:     0x7fa79e095ea1 - io::BufRead::read_line::closure.14338
                        at ../src/libstd/io/mod.rs:1405
  14:     0x7fa79e095c59 - io::append_to_string::h16196573818836934124
                        at ../src/libstd/io/mod.rs:309
  15:     0x7fa79e095beb - io::BufRead::read_line::h3863305996463976303
                        at ../src/libstd/io/mod.rs:1405
...
```

the line it refers to is [this one](https://github.com/alexcrichton/flate2-rs/blob/af3c4b906b89fa5321e45b50ea49bb0772f55d98/src/crc.rs#L33)

**Comment by flying-sheep** [comment]
@alexcrichton could you please do a release 0.2.10 with this?

**Comment by alexcrichton** [comment]
Certainly!

**Comment by flying-sheep** [comment]
thank you!
